# Generated by Django 5.2 on 2025-04-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
