# Generated by Django 5.2 on 2025-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
