# Generated by Django 5.2 on 2025-05-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_remove_category_descr_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='deals.deal'),
        ),
    ]
