# Generated by Django 5.2 on 2025-05-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deals.deal'),
        ),
    ]
